program: main.py

method: bayes
metric:
  name: test_acc.max
  goal: maximize
parameters:
  pool_size:
    values: [10]
  top_k:
    values: [2,4]
  num_outer_loops:
    values: [5]

command:
  - ${env}
  - python3
  - main.py
  - "--task"
  - "food101_cnum20_dist0_skew0_seed0_missing_ratio_0.7_0.7_missing_type_both_both_both_ratio_0.5"
  - "--model"
  - "Fed-Prime"
  - "--algorithm"
  - "multimodal.food101.Fed-Prime"
  - "--sample"
  - "full"
  - "--aggregate"
  - "other"
  - "--num_rounds"
  - "2"
  - "--proportion"
  - "1.0"
  - "--lr_scheduler"
  - "0"
  - "--seed"
  - "1234"
  - "--num_epochs"
  - "1"
  - "--learning_rate"
  - "0.05"
  - "--learning_rate_decay"
  - "1.0"
  - "--batch_size"
  - "128"
  - "--test_batch_size"
  - "128"
  - "--max_text_len"
  - "40"
  - "--gpu"
  - "1"
  - "--wandb"

